version: '3'

services:
  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network

  app:
    build:
      args:
        user: www
        uid: 1000
      context: ./
      dockerfile: Dockerfile.fpm
    image: fpm-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./php-fpm.conf:/usr/local/etc/conf.d/php-fpm.conf
      - ./laravel-app .
    networks:
      - laravel_network

  db:
    image: postgres:15.5
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=laravel
    networks:
      - laravel_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.11
    networks:
      - laravel_network

  supervisor:
    build:
      context: .
      dockerfile: Dockerfile.supervisor
    image: supervisor
    networks:
      - laravel_network

networks:
  laravel_network:

volumes:
  pgdata:
